### ISSUE TITLE
ddocus: command not found

### ISSUE THREAD

**Issue by dannymcc** [lyonrb/deploy_docus#5]
After successfully installing the gem, I get `ddocus: command not found`when I run ddocus new app_name.

``` ruby
dannymcclelland@macbookpro ~/projects$ ddocus new deploy
-bash: ddocus: command not found
```

Am I missing any vital steps?

**Comment by dmathieu** [comment]
This should be fixed by 5fe2c5b381f654326dbf038aa0babd43041730f5
Can you pull the repository, install the gem from it and confirm ?

**Comment by dannymcc** [comment]
How do I install the gem from source?

**Comment by dannymcc** [comment]
Google was my friend but no luck:

``` ruby
dannymcclelland@macbookpro ~/Projects/deploy_docus[master]$ gem build deploy_docus.gemspec
  Successfully built RubyGem
  Name: deploy_docus
  Version: 0.0.8
  File: deploy_docus-0.0.8.gem
dannymcclelland@macbookpro ~/Projects/deploy_docus[master*]$ gem install deploy_docus-0.0.8.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /Library/Ruby/Gems/1.8 directory.
dannymcclelland@macbookpro ~/Projects/deploy_docus[master*]$ sudo !!
sudo gem install deploy_docus-0.0.8.gem
Password:
Successfully installed deploy_docus-0.0.8
1 gem installed
Installing ri documentation for deploy_docus-0.0.8...
Installing RDoc documentation for deploy_docus-0.0.8...
dannymcclelland@macbookpro ~/Projects/deploy_docus[master*]$ ddocus new deployment
-bash: ddocus: command not found
dannymcclelland@macbookpro ~/Projects/deploy_docus[master*]$ 
```

**Comment by dmathieu** [comment]
That's fixed, pushed and deployed. Thanks for the report :)

**Comment by dannymcc** [comment]
I'm still getting this problem. You can see the full breakdown of the steps I took here: https://gist.github.com/1327224

**Comment by dmathieu** [comment]
```
dannymcclelland@macbookpro ~/Projects/deploy_docus[master*]$ gem install docus_deploy
ERROR:  Could not find a valid gem 'docus_deploy' (>= 0) in any repository
```

it's `gem install deploy_docus`. Not `docus_deploy`.
